package com.website.batch.entity;

import java.util.ArrayList;
import java.util.List;

public class JobEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    public JobEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    public JobEntityExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    public JobEntityExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        JobEntityExample example = new JobEntityExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    public JobEntityExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    public JobEntityExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andIdEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("ID = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andIdNotEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("ID <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andIdGreaterThanColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("ID > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andIdGreaterThanOrEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("ID >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andIdLessThanColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("ID < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andIdLessThanOrEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("ID <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`NAME` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`NAME` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`NAME` =", value, "name");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andNameEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("`NAME` = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`NAME` <>", value, "name");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andNameNotEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("`NAME` <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`NAME` >", value, "name");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andNameGreaterThanColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("`NAME` > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`NAME` >=", value, "name");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andNameGreaterThanOrEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("`NAME` >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`NAME` <", value, "name");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andNameLessThanColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("`NAME` < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`NAME` <=", value, "name");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andNameLessThanOrEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("`NAME` <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`NAME` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`NAME` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`NAME` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`NAME` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`NAME` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`NAME` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andJobGroupIsNull() {
            addCriterion("JOB_GROUP is null");
            return (Criteria) this;
        }

        public Criteria andJobGroupIsNotNull() {
            addCriterion("JOB_GROUP is not null");
            return (Criteria) this;
        }

        public Criteria andJobGroupEqualTo(String value) {
            addCriterion("JOB_GROUP =", value, "jobGroup");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andJobGroupEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("JOB_GROUP = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJobGroupNotEqualTo(String value) {
            addCriterion("JOB_GROUP <>", value, "jobGroup");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andJobGroupNotEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("JOB_GROUP <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJobGroupGreaterThan(String value) {
            addCriterion("JOB_GROUP >", value, "jobGroup");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andJobGroupGreaterThanColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("JOB_GROUP > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJobGroupGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_GROUP >=", value, "jobGroup");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andJobGroupGreaterThanOrEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("JOB_GROUP >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJobGroupLessThan(String value) {
            addCriterion("JOB_GROUP <", value, "jobGroup");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andJobGroupLessThanColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("JOB_GROUP < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJobGroupLessThanOrEqualTo(String value) {
            addCriterion("JOB_GROUP <=", value, "jobGroup");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andJobGroupLessThanOrEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("JOB_GROUP <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJobGroupLike(String value) {
            addCriterion("JOB_GROUP like", value, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupNotLike(String value) {
            addCriterion("JOB_GROUP not like", value, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupIn(List<String> values) {
            addCriterion("JOB_GROUP in", values, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupNotIn(List<String> values) {
            addCriterion("JOB_GROUP not in", values, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupBetween(String value1, String value2) {
            addCriterion("JOB_GROUP between", value1, value2, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupNotBetween(String value1, String value2) {
            addCriterion("JOB_GROUP not between", value1, value2, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobNameIsNull() {
            addCriterion("JOB_NAME is null");
            return (Criteria) this;
        }

        public Criteria andJobNameIsNotNull() {
            addCriterion("JOB_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andJobNameEqualTo(String value) {
            addCriterion("JOB_NAME =", value, "jobName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andJobNameEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("JOB_NAME = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJobNameNotEqualTo(String value) {
            addCriterion("JOB_NAME <>", value, "jobName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andJobNameNotEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("JOB_NAME <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJobNameGreaterThan(String value) {
            addCriterion("JOB_NAME >", value, "jobName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andJobNameGreaterThanColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("JOB_NAME > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJobNameGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_NAME >=", value, "jobName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andJobNameGreaterThanOrEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("JOB_NAME >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJobNameLessThan(String value) {
            addCriterion("JOB_NAME <", value, "jobName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andJobNameLessThanColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("JOB_NAME < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJobNameLessThanOrEqualTo(String value) {
            addCriterion("JOB_NAME <=", value, "jobName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andJobNameLessThanOrEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("JOB_NAME <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJobNameLike(String value) {
            addCriterion("JOB_NAME like", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotLike(String value) {
            addCriterion("JOB_NAME not like", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameIn(List<String> values) {
            addCriterion("JOB_NAME in", values, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotIn(List<String> values) {
            addCriterion("JOB_NAME not in", values, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameBetween(String value1, String value2) {
            addCriterion("JOB_NAME between", value1, value2, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotBetween(String value1, String value2) {
            addCriterion("JOB_NAME not between", value1, value2, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobCronIsNull() {
            addCriterion("JOB_CRON is null");
            return (Criteria) this;
        }

        public Criteria andJobCronIsNotNull() {
            addCriterion("JOB_CRON is not null");
            return (Criteria) this;
        }

        public Criteria andJobCronEqualTo(String value) {
            addCriterion("JOB_CRON =", value, "jobCron");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andJobCronEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("JOB_CRON = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJobCronNotEqualTo(String value) {
            addCriterion("JOB_CRON <>", value, "jobCron");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andJobCronNotEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("JOB_CRON <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJobCronGreaterThan(String value) {
            addCriterion("JOB_CRON >", value, "jobCron");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andJobCronGreaterThanColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("JOB_CRON > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJobCronGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_CRON >=", value, "jobCron");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andJobCronGreaterThanOrEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("JOB_CRON >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJobCronLessThan(String value) {
            addCriterion("JOB_CRON <", value, "jobCron");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andJobCronLessThanColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("JOB_CRON < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJobCronLessThanOrEqualTo(String value) {
            addCriterion("JOB_CRON <=", value, "jobCron");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andJobCronLessThanOrEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("JOB_CRON <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJobCronLike(String value) {
            addCriterion("JOB_CRON like", value, "jobCron");
            return (Criteria) this;
        }

        public Criteria andJobCronNotLike(String value) {
            addCriterion("JOB_CRON not like", value, "jobCron");
            return (Criteria) this;
        }

        public Criteria andJobCronIn(List<String> values) {
            addCriterion("JOB_CRON in", values, "jobCron");
            return (Criteria) this;
        }

        public Criteria andJobCronNotIn(List<String> values) {
            addCriterion("JOB_CRON not in", values, "jobCron");
            return (Criteria) this;
        }

        public Criteria andJobCronBetween(String value1, String value2) {
            addCriterion("JOB_CRON between", value1, value2, "jobCron");
            return (Criteria) this;
        }

        public Criteria andJobCronNotBetween(String value1, String value2) {
            addCriterion("JOB_CRON not between", value1, value2, "jobCron");
            return (Criteria) this;
        }

        public Criteria andParamerterIsNull() {
            addCriterion("PARAMERTER is null");
            return (Criteria) this;
        }

        public Criteria andParamerterIsNotNull() {
            addCriterion("PARAMERTER is not null");
            return (Criteria) this;
        }

        public Criteria andParamerterEqualTo(String value) {
            addCriterion("PARAMERTER =", value, "paramerter");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andParamerterEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("PARAMERTER = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andParamerterNotEqualTo(String value) {
            addCriterion("PARAMERTER <>", value, "paramerter");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andParamerterNotEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("PARAMERTER <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andParamerterGreaterThan(String value) {
            addCriterion("PARAMERTER >", value, "paramerter");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andParamerterGreaterThanColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("PARAMERTER > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andParamerterGreaterThanOrEqualTo(String value) {
            addCriterion("PARAMERTER >=", value, "paramerter");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andParamerterGreaterThanOrEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("PARAMERTER >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andParamerterLessThan(String value) {
            addCriterion("PARAMERTER <", value, "paramerter");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andParamerterLessThanColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("PARAMERTER < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andParamerterLessThanOrEqualTo(String value) {
            addCriterion("PARAMERTER <=", value, "paramerter");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andParamerterLessThanOrEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("PARAMERTER <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andParamerterLike(String value) {
            addCriterion("PARAMERTER like", value, "paramerter");
            return (Criteria) this;
        }

        public Criteria andParamerterNotLike(String value) {
            addCriterion("PARAMERTER not like", value, "paramerter");
            return (Criteria) this;
        }

        public Criteria andParamerterIn(List<String> values) {
            addCriterion("PARAMERTER in", values, "paramerter");
            return (Criteria) this;
        }

        public Criteria andParamerterNotIn(List<String> values) {
            addCriterion("PARAMERTER not in", values, "paramerter");
            return (Criteria) this;
        }

        public Criteria andParamerterBetween(String value1, String value2) {
            addCriterion("PARAMERTER between", value1, value2, "paramerter");
            return (Criteria) this;
        }

        public Criteria andParamerterNotBetween(String value1, String value2) {
            addCriterion("PARAMERTER not between", value1, value2, "paramerter");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "description");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andDescriptionEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("DESCRIPTION = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "description");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andDescriptionNotEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("DESCRIPTION <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "description");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andDescriptionGreaterThanColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("DESCRIPTION > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "description");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andDescriptionGreaterThanOrEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("DESCRIPTION >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "description");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andDescriptionLessThanColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("DESCRIPTION < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "description");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andDescriptionLessThanOrEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("DESCRIPTION <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("DESCRIPTION like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("DESCRIPTION in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("DESCRIPTION not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andVmParamIsNull() {
            addCriterion("VM_PARAM is null");
            return (Criteria) this;
        }

        public Criteria andVmParamIsNotNull() {
            addCriterion("VM_PARAM is not null");
            return (Criteria) this;
        }

        public Criteria andVmParamEqualTo(String value) {
            addCriterion("VM_PARAM =", value, "vmParam");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andVmParamEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("VM_PARAM = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVmParamNotEqualTo(String value) {
            addCriterion("VM_PARAM <>", value, "vmParam");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andVmParamNotEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("VM_PARAM <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVmParamGreaterThan(String value) {
            addCriterion("VM_PARAM >", value, "vmParam");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andVmParamGreaterThanColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("VM_PARAM > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVmParamGreaterThanOrEqualTo(String value) {
            addCriterion("VM_PARAM >=", value, "vmParam");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andVmParamGreaterThanOrEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("VM_PARAM >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVmParamLessThan(String value) {
            addCriterion("VM_PARAM <", value, "vmParam");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andVmParamLessThanColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("VM_PARAM < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVmParamLessThanOrEqualTo(String value) {
            addCriterion("VM_PARAM <=", value, "vmParam");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andVmParamLessThanOrEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("VM_PARAM <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVmParamLike(String value) {
            addCriterion("VM_PARAM like", value, "vmParam");
            return (Criteria) this;
        }

        public Criteria andVmParamNotLike(String value) {
            addCriterion("VM_PARAM not like", value, "vmParam");
            return (Criteria) this;
        }

        public Criteria andVmParamIn(List<String> values) {
            addCriterion("VM_PARAM in", values, "vmParam");
            return (Criteria) this;
        }

        public Criteria andVmParamNotIn(List<String> values) {
            addCriterion("VM_PARAM not in", values, "vmParam");
            return (Criteria) this;
        }

        public Criteria andVmParamBetween(String value1, String value2) {
            addCriterion("VM_PARAM between", value1, value2, "vmParam");
            return (Criteria) this;
        }

        public Criteria andVmParamNotBetween(String value1, String value2) {
            addCriterion("VM_PARAM not between", value1, value2, "vmParam");
            return (Criteria) this;
        }

        public Criteria andJarPathIsNull() {
            addCriterion("JAR_PATH is null");
            return (Criteria) this;
        }

        public Criteria andJarPathIsNotNull() {
            addCriterion("JAR_PATH is not null");
            return (Criteria) this;
        }

        public Criteria andJarPathEqualTo(String value) {
            addCriterion("JAR_PATH =", value, "jarPath");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andJarPathEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("JAR_PATH = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJarPathNotEqualTo(String value) {
            addCriterion("JAR_PATH <>", value, "jarPath");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andJarPathNotEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("JAR_PATH <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJarPathGreaterThan(String value) {
            addCriterion("JAR_PATH >", value, "jarPath");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andJarPathGreaterThanColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("JAR_PATH > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJarPathGreaterThanOrEqualTo(String value) {
            addCriterion("JAR_PATH >=", value, "jarPath");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andJarPathGreaterThanOrEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("JAR_PATH >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJarPathLessThan(String value) {
            addCriterion("JAR_PATH <", value, "jarPath");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andJarPathLessThanColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("JAR_PATH < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJarPathLessThanOrEqualTo(String value) {
            addCriterion("JAR_PATH <=", value, "jarPath");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andJarPathLessThanOrEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("JAR_PATH <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJarPathLike(String value) {
            addCriterion("JAR_PATH like", value, "jarPath");
            return (Criteria) this;
        }

        public Criteria andJarPathNotLike(String value) {
            addCriterion("JAR_PATH not like", value, "jarPath");
            return (Criteria) this;
        }

        public Criteria andJarPathIn(List<String> values) {
            addCriterion("JAR_PATH in", values, "jarPath");
            return (Criteria) this;
        }

        public Criteria andJarPathNotIn(List<String> values) {
            addCriterion("JAR_PATH not in", values, "jarPath");
            return (Criteria) this;
        }

        public Criteria andJarPathBetween(String value1, String value2) {
            addCriterion("JAR_PATH between", value1, value2, "jarPath");
            return (Criteria) this;
        }

        public Criteria andJarPathNotBetween(String value1, String value2) {
            addCriterion("JAR_PATH not between", value1, value2, "jarPath");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andStatusEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("STATUS = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andStatusNotEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("STATUS <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andStatusGreaterThanColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("STATUS > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andStatusGreaterThanOrEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("STATUS >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andStatusLessThanColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("STATUS < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andStatusLessThanOrEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("STATUS <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("CREATE_TIME = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeNotEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("CREATE_TIME <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeGreaterThanColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("CREATE_TIME > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeGreaterThanOrEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("CREATE_TIME >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeLessThanColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("CREATE_TIME < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeLessThanOrEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("CREATE_TIME <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("CREATE_TIME like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("CREATE_TIME not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(String value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("UPDATE_TIME = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(String value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeNotEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("UPDATE_TIME <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(String value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeGreaterThanColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("UPDATE_TIME > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeGreaterThanOrEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("UPDATE_TIME >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(String value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeLessThanColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("UPDATE_TIME < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeLessThanOrEqualToColumn(JobEntity.Column column) {
            addCriterion(new StringBuilder("UPDATE_TIME <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLike(String value) {
            addCriterion("UPDATE_TIME like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotLike(String value) {
            addCriterion("UPDATE_TIME not like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<String> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<String> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(String value1, String value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(String value1, String value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        private JobEntityExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        protected Criteria(JobEntityExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public JobEntityExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table QRTZ_JOB_ENTITY
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table QRTZ_JOB_ENTITY
         *
         * @mbg.generated
         */
        void example(JobEntityExample example);
    }
}
