package com.website.batch.entity;

import java.util.ArrayList;
import java.util.Arrays;

public class NetEaseSongListRel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SONG_LIST_REL.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SONG_LIST_REL.SONG_LIST_ID
     *
     * @mbg.generated
     */
    private String songListId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SONG_LIST_REL.SONG_ID
     *
     * @mbg.generated
     */
    private String songId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SONG_LIST_REL.SEND_FLAG
     *
     * @mbg.generated
     */
    private String sendFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SONG_LIST_REL.CREATE_TIME
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SONG_LIST_REL.UPDATE_TIME
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SONG_LIST_REL.ID
     *
     * @return the value of SONG_LIST_REL.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SONG_LIST_REL.ID
     *
     * @param id the value for SONG_LIST_REL.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SONG_LIST_REL.SONG_LIST_ID
     *
     * @return the value of SONG_LIST_REL.SONG_LIST_ID
     *
     * @mbg.generated
     */
    public String getSongListId() {
        return songListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SONG_LIST_REL.SONG_LIST_ID
     *
     * @param songListId the value for SONG_LIST_REL.SONG_LIST_ID
     *
     * @mbg.generated
     */
    public void setSongListId(String songListId) {
        this.songListId = songListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SONG_LIST_REL.SONG_ID
     *
     * @return the value of SONG_LIST_REL.SONG_ID
     *
     * @mbg.generated
     */
    public String getSongId() {
        return songId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SONG_LIST_REL.SONG_ID
     *
     * @param songId the value for SONG_LIST_REL.SONG_ID
     *
     * @mbg.generated
     */
    public void setSongId(String songId) {
        this.songId = songId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SONG_LIST_REL.SEND_FLAG
     *
     * @return the value of SONG_LIST_REL.SEND_FLAG
     *
     * @mbg.generated
     */
    public String getSendFlag() {
        return sendFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SONG_LIST_REL.SEND_FLAG
     *
     * @param sendFlag the value for SONG_LIST_REL.SEND_FLAG
     *
     * @mbg.generated
     */
    public void setSendFlag(String sendFlag) {
        this.sendFlag = sendFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SONG_LIST_REL.CREATE_TIME
     *
     * @return the value of SONG_LIST_REL.CREATE_TIME
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SONG_LIST_REL.CREATE_TIME
     *
     * @param createTime the value for SONG_LIST_REL.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SONG_LIST_REL.UPDATE_TIME
     *
     * @return the value of SONG_LIST_REL.UPDATE_TIME
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SONG_LIST_REL.UPDATE_TIME
     *
     * @param updateTime the value for SONG_LIST_REL.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SONG_LIST_REL
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", songListId=").append(songListId);
        sb.append(", songId=").append(songId);
        sb.append(", sendFlag=").append(sendFlag);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SONG_LIST_REL
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NetEaseSongListRel other = (NetEaseSongListRel) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSongListId() == null ? other.getSongListId() == null : this.getSongListId().equals(other.getSongListId()))
            && (this.getSongId() == null ? other.getSongId() == null : this.getSongId().equals(other.getSongId()))
            && (this.getSendFlag() == null ? other.getSendFlag() == null : this.getSendFlag().equals(other.getSendFlag()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SONG_LIST_REL
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSongListId() == null) ? 0 : getSongListId().hashCode());
        result = prime * result + ((getSongId() == null) ? 0 : getSongId().hashCode());
        result = prime * result + ((getSendFlag() == null) ? 0 : getSendFlag().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table SONG_LIST_REL
     *
     * @mbg.generated
     */
    public enum Column {
        id("ID", "id", "VARCHAR", false),
        songListId("SONG_LIST_ID", "songListId", "VARCHAR", false),
        songId("SONG_ID", "songId", "VARCHAR", false),
        sendFlag("SEND_FLAG", "sendFlag", "VARCHAR", false),
        createTime("CREATE_TIME", "createTime", "VARCHAR", false),
        updateTime("UPDATE_TIME", "updateTime", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table SONG_LIST_REL
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table SONG_LIST_REL
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table SONG_LIST_REL
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table SONG_LIST_REL
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table SONG_LIST_REL
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table SONG_LIST_REL
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_LIST_REL
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_LIST_REL
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_LIST_REL
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_LIST_REL
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_LIST_REL
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_LIST_REL
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_LIST_REL
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_LIST_REL
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_LIST_REL
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_LIST_REL
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}