package com.website.batch.entity;

import java.util.ArrayList;
import java.util.Arrays;

public class NetEaseSongDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SONG_DETAIL.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SONG_DETAIL.SONG_ID
     *
     * @mbg.generated
     */
    private String songId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SONG_DETAIL.SONG_NAME
     *
     * @mbg.generated
     */
    private String songName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SONG_DETAIL.SONG_SINGER
     *
     * @mbg.generated
     */
    private String songSinger;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SONG_DETAIL.CREATE_TIME
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SONG_DETAIL.UPDATE_TIME
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SONG_DETAIL.ID
     *
     * @return the value of SONG_DETAIL.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SONG_DETAIL.ID
     *
     * @param id the value for SONG_DETAIL.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SONG_DETAIL.SONG_ID
     *
     * @return the value of SONG_DETAIL.SONG_ID
     *
     * @mbg.generated
     */
    public String getSongId() {
        return songId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SONG_DETAIL.SONG_ID
     *
     * @param songId the value for SONG_DETAIL.SONG_ID
     *
     * @mbg.generated
     */
    public void setSongId(String songId) {
        this.songId = songId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SONG_DETAIL.SONG_NAME
     *
     * @return the value of SONG_DETAIL.SONG_NAME
     *
     * @mbg.generated
     */
    public String getSongName() {
        return songName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SONG_DETAIL.SONG_NAME
     *
     * @param songName the value for SONG_DETAIL.SONG_NAME
     *
     * @mbg.generated
     */
    public void setSongName(String songName) {
        this.songName = songName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SONG_DETAIL.SONG_SINGER
     *
     * @return the value of SONG_DETAIL.SONG_SINGER
     *
     * @mbg.generated
     */
    public String getSongSinger() {
        return songSinger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SONG_DETAIL.SONG_SINGER
     *
     * @param songSinger the value for SONG_DETAIL.SONG_SINGER
     *
     * @mbg.generated
     */
    public void setSongSinger(String songSinger) {
        this.songSinger = songSinger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SONG_DETAIL.CREATE_TIME
     *
     * @return the value of SONG_DETAIL.CREATE_TIME
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SONG_DETAIL.CREATE_TIME
     *
     * @param createTime the value for SONG_DETAIL.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SONG_DETAIL.UPDATE_TIME
     *
     * @return the value of SONG_DETAIL.UPDATE_TIME
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SONG_DETAIL.UPDATE_TIME
     *
     * @param updateTime the value for SONG_DETAIL.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SONG_DETAIL
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", songId=").append(songId);
        sb.append(", songName=").append(songName);
        sb.append(", songSinger=").append(songSinger);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SONG_DETAIL
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NetEaseSongDetail other = (NetEaseSongDetail) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSongId() == null ? other.getSongId() == null : this.getSongId().equals(other.getSongId()))
            && (this.getSongName() == null ? other.getSongName() == null : this.getSongName().equals(other.getSongName()))
            && (this.getSongSinger() == null ? other.getSongSinger() == null : this.getSongSinger().equals(other.getSongSinger()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SONG_DETAIL
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSongId() == null) ? 0 : getSongId().hashCode());
        result = prime * result + ((getSongName() == null) ? 0 : getSongName().hashCode());
        result = prime * result + ((getSongSinger() == null) ? 0 : getSongSinger().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table SONG_DETAIL
     *
     * @mbg.generated
     */
    public enum Column {
        id("ID", "id", "VARCHAR", false),
        songId("SONG_ID", "songId", "VARCHAR", false),
        songName("SONG_NAME", "songName", "VARCHAR", false),
        songSinger("SONG_SINGER", "songSinger", "VARCHAR", false),
        createTime("CREATE_TIME", "createTime", "VARCHAR", false),
        updateTime("UPDATE_TIME", "updateTime", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table SONG_DETAIL
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table SONG_DETAIL
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table SONG_DETAIL
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table SONG_DETAIL
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table SONG_DETAIL
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table SONG_DETAIL
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_DETAIL
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_DETAIL
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_DETAIL
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_DETAIL
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_DETAIL
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_DETAIL
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_DETAIL
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_DETAIL
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_DETAIL
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_DETAIL
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}