package com.website.batch.entity;

import java.util.ArrayList;
import java.util.Arrays;

public class NetEaseSongList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SONG_LIST.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SONG_LIST.LIST_ID
     *
     * @mbg.generated
     */
    private String listId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SONG_LIST.LIST_NAME
     *
     * @mbg.generated
     */
    private String listName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SONG_LIST.LSIT_DESC
     *
     * @mbg.generated
     */
    private String lsitDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SONG_LIST.CREATE_USER
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SONG_LIST.CREATE_USER_ID
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SONG_LIST.CREATE_TIME
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SONG_LIST.UPDATE_TIME
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SONG_LIST.ID
     *
     * @return the value of SONG_LIST.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SONG_LIST.ID
     *
     * @param id the value for SONG_LIST.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SONG_LIST.LIST_ID
     *
     * @return the value of SONG_LIST.LIST_ID
     *
     * @mbg.generated
     */
    public String getListId() {
        return listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SONG_LIST.LIST_ID
     *
     * @param listId the value for SONG_LIST.LIST_ID
     *
     * @mbg.generated
     */
    public void setListId(String listId) {
        this.listId = listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SONG_LIST.LIST_NAME
     *
     * @return the value of SONG_LIST.LIST_NAME
     *
     * @mbg.generated
     */
    public String getListName() {
        return listName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SONG_LIST.LIST_NAME
     *
     * @param listName the value for SONG_LIST.LIST_NAME
     *
     * @mbg.generated
     */
    public void setListName(String listName) {
        this.listName = listName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SONG_LIST.LSIT_DESC
     *
     * @return the value of SONG_LIST.LSIT_DESC
     *
     * @mbg.generated
     */
    public String getLsitDesc() {
        return lsitDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SONG_LIST.LSIT_DESC
     *
     * @param lsitDesc the value for SONG_LIST.LSIT_DESC
     *
     * @mbg.generated
     */
    public void setLsitDesc(String lsitDesc) {
        this.lsitDesc = lsitDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SONG_LIST.CREATE_USER
     *
     * @return the value of SONG_LIST.CREATE_USER
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SONG_LIST.CREATE_USER
     *
     * @param createUser the value for SONG_LIST.CREATE_USER
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SONG_LIST.CREATE_USER_ID
     *
     * @return the value of SONG_LIST.CREATE_USER_ID
     *
     * @mbg.generated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SONG_LIST.CREATE_USER_ID
     *
     * @param createUserId the value for SONG_LIST.CREATE_USER_ID
     *
     * @mbg.generated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SONG_LIST.CREATE_TIME
     *
     * @return the value of SONG_LIST.CREATE_TIME
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SONG_LIST.CREATE_TIME
     *
     * @param createTime the value for SONG_LIST.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SONG_LIST.UPDATE_TIME
     *
     * @return the value of SONG_LIST.UPDATE_TIME
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SONG_LIST.UPDATE_TIME
     *
     * @param updateTime the value for SONG_LIST.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SONG_LIST
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", listId=").append(listId);
        sb.append(", listName=").append(listName);
        sb.append(", lsitDesc=").append(lsitDesc);
        sb.append(", createUser=").append(createUser);
        sb.append(", createUserId=").append(createUserId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SONG_LIST
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NetEaseSongList other = (NetEaseSongList) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getListId() == null ? other.getListId() == null : this.getListId().equals(other.getListId()))
            && (this.getListName() == null ? other.getListName() == null : this.getListName().equals(other.getListName()))
            && (this.getLsitDesc() == null ? other.getLsitDesc() == null : this.getLsitDesc().equals(other.getLsitDesc()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getCreateUserId() == null ? other.getCreateUserId() == null : this.getCreateUserId().equals(other.getCreateUserId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SONG_LIST
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getListId() == null) ? 0 : getListId().hashCode());
        result = prime * result + ((getListName() == null) ? 0 : getListName().hashCode());
        result = prime * result + ((getLsitDesc() == null) ? 0 : getLsitDesc().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getCreateUserId() == null) ? 0 : getCreateUserId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table SONG_LIST
     *
     * @mbg.generated
     */
    public enum Column {
        id("ID", "id", "VARCHAR", false),
        listId("LIST_ID", "listId", "VARCHAR", false),
        listName("LIST_NAME", "listName", "VARCHAR", false),
        lsitDesc("LSIT_DESC", "lsitDesc", "VARCHAR", false),
        createUser("CREATE_USER", "createUser", "VARCHAR", false),
        createUserId("CREATE_USER_ID", "createUserId", "VARCHAR", false),
        createTime("CREATE_TIME", "createTime", "VARCHAR", false),
        updateTime("UPDATE_TIME", "updateTime", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table SONG_LIST
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table SONG_LIST
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table SONG_LIST
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table SONG_LIST
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table SONG_LIST
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table SONG_LIST
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_LIST
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_LIST
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_LIST
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_LIST
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_LIST
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_LIST
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_LIST
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_LIST
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_LIST
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SONG_LIST
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}