quartz:
  enabled: true
server:
  port: 8012
spring:
  application:
    name: Spring-Quartz-Scheduler                                       #Quartz调度中心
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ip:port/website-test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
    tomcat:
      initialSize: 20
      maxActive: 100
      maxIdle: 100
      minIdle: 20
      maxWait: 10000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
  mail:
    host: smtp.qq.com
    port: 587
    username: 386477518@qq.com
    nickname: '关注提醒机器人X'
    password:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#日志
logging:
  file:
    name: /opt/logs/website-batch.log

mybatis:
  type-aliases-package: com.website.batch.entity
  mapperLocations: classpath:mapper/*.xml

