package com.website.batch.mapper;

import com.website.batch.entity.JobEntity;
import com.website.batch.entity.JobEntityExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface JobEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    long countByExample(JobEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    int deleteByExample(JobEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    int insert(JobEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    int insertSelective(JobEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    JobEntity selectOneByExample(JobEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    JobEntity selectOneByExampleSelective(@Param("example") JobEntityExample example, @Param("selective") JobEntity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    List<JobEntity> selectByExampleSelective(@Param("example") JobEntityExample example, @Param("selective") JobEntity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    List<JobEntity> selectByExample(JobEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    JobEntity selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JobEntity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    JobEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JobEntity record, @Param("example") JobEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JobEntity record, @Param("example") JobEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JobEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_ENTITY
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JobEntity record);
}