package com.website.batch.mapper;

import com.website.batch.entity.NetEaseSongList;
import com.website.batch.entity.NetEaseSongListExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface NetEaseSongListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SONG_LIST
     *
     * @mbg.generated
     */
    long countByExample(NetEaseSongListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SONG_LIST
     *
     * @mbg.generated
     */
    int deleteByExample(NetEaseSongListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SONG_LIST
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SONG_LIST
     *
     * @mbg.generated
     */
    int insert(NetEaseSongList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SONG_LIST
     *
     * @mbg.generated
     */
    int insertSelective(NetEaseSongList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SONG_LIST
     *
     * @mbg.generated
     */
    NetEaseSongList selectOneByExample(NetEaseSongListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SONG_LIST
     *
     * @mbg.generated
     */
    NetEaseSongList selectOneByExampleSelective(@Param("example") NetEaseSongListExample example, @Param("selective") NetEaseSongList.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SONG_LIST
     *
     * @mbg.generated
     */
    List<NetEaseSongList> selectByExampleSelective(@Param("example") NetEaseSongListExample example, @Param("selective") NetEaseSongList.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SONG_LIST
     *
     * @mbg.generated
     */
    List<NetEaseSongList> selectByExample(NetEaseSongListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SONG_LIST
     *
     * @mbg.generated
     */
    NetEaseSongList selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") NetEaseSongList.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SONG_LIST
     *
     * @mbg.generated
     */
    NetEaseSongList selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SONG_LIST
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") NetEaseSongList record, @Param("example") NetEaseSongListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SONG_LIST
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") NetEaseSongList record, @Param("example") NetEaseSongListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SONG_LIST
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NetEaseSongList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SONG_LIST
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NetEaseSongList record);
}